---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
#  - name: bionic64
#    box: ubuntu/bionic64
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: true
verifier:
  name: goss
