---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
#  - name: stretch64
#    box: debian/stretch64
#  - name: jessie64
#    box: debian/jessie64
#  - name: xenial64
#    box: ubuntu/xenial64
#  - name: bionic64
#    box: ubuntu/bionic64
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  become: true
verifier:
  name: goss
